README.md
=> Modify Reason: 更新仓库Readme，增加22讲和23讲索引

01_HelloWeb3/readme.md
remix.ethereum.org -> https://remix.ethereum.org
來為WTF做貢獻
=> fix remix link in readme

03_Function/readme.md
readme内容number和_number 与 .sol合约文件中不一致
=> fix issue: readme内容number和_number 与 .sol合约文件中不一致

04_Return/readme.md
=> Update 04 readme

22_Call/readme.md
=> fix-22讲两处跳转链接错误

11_Modifier/readme.md
=> fix-11 readme.md的构造函数代码和Owner.sol同步

24_Create/readme.md, 25_Create2/readme.md
=> 24章节 25 章节 图片引述错误

05_DataStorage/readme.md
=> 增加Now的使用说明

33_Airdrop/Airdrop.sol, 33_Airdrop/readme.md
=> Equal condition shoud be allowed

29_Selector/Selector.sol
=> fix warning unused paramater

38_NFTSwap/readme.md
感觉之前remix内容补充的不太充实，重新加上方法说明，以及调用案例说明。
=> 更新课程38讲，审核教程以及语病，补充remix部分内容

05_DataStorage/DataStorage.sol
=> Issues #121 Fixed

03_Function/readme.md
=> add the function visibility

Languages/en/03_Function_en/readme.md, Languages/en/04_Return_en/readme.md, Languages/en/05_DataStorage_en/readme.md, Languages/en/06_ArrayAndStruct_en/readme.md
Copy edits for the english translation as requested by Zerohash.x
=> English review for sections 3-6

18_Import/Yeye.sol
fix comments for 'import' chapter
=> fix comments

15_Errors/Error.sol, 15_Errors/readme.md
add error with parameters and more clear description about gas cost amount
=> 为Error篇章添加了带参数的Error,以及添加了Gas cost数值测算的编译器版本

Topics/Tools/TOOL03_Ganache/readme.md
Additional for the tool [Ganache](https://github.com/AmazingAng/WTFSolidity/blob/main/Topics/Tools/TOOL03_Ganache/readme.md).
- Improved description of main features.
- Added details for "Fast Forward Time" features.
Please see here [https://github.com/u-u-z/WTFSolidity/tree/patch/topic/tools/ganache/Topics/Tools/TOOL03_Ganache](https://github.com/u-u-z/WTFSolidity/tree/patch/topic/tools/ganache/Topics/Tools/TOOL03_Ganache)
=> UPDATE: Ganache tool tutorials in "Topics/Tools/TOOL03_Ganache/readme.md"

Topics/Tools/TOOL06_Hardhat/hardhat.config.js, Topics/Tools/TOOL06_Hardhat/readme.md, Topics/Tools/TOOL06_Hardhat/scripts/deploy.js
1. 新增了使用hardhat编写测试脚本，在本地进行部署
2. 新增了自定义测试网络的配置，配置Goerli网络，并在Goerli网络进行部署
=> 新增 部署合约 和 测试网络配置

Topics/Tools/TOOL06_Hardhat/readme.md
我认为这里应该是进入目录去初始化npm以及下载hardhat。而不是在目录外面。
=> 修改hardhat ReadMe.md

25_Create2/readme.md
=> 更换链接地址，原地址为编辑地址

36_MerkleTree/readme.md
Add more details for how Merkle Proof is determined
=> Add more details for Merkle Proof

13_Inheritance/readme.md
修饰器exactDividedBy2And3限制传入的参数必须是2和3的倍数，需加修饰器内容
=> 13讲 modifier override

05_DataStorage/readme.md
=> typo: 复本 改为  副本

35_DutchAuction/DutchAuction.sol, 35_DutchAuction/readme.md
=> update getAuctionPrice, auctionMint, readme

Topics/Tools/TOOL07_Foundry/readme.md
* 新增 forge 常用命令行的使用
* 新增 console2.log的使用案例
* 新增 test case 常用小技巧
* 新增脚本部署的案例
=> Added foundry forge&&anvil  usage

25_Create2/readme.md
更新：
25课 create2生成合约时 合约构造函数存在输入时，在预测地址时的改变
=> update leasson25 create2

30_TryCatch/TryCatch.sol, 30_TryCatch/readme.md
https://github.com/AmazingAng/WTF-Solidity/issues/281
=> 修改catch支持捕获特殊的异常原因中的不准确描述

S11_SilentFailingSendsAndUnchecked-SendAttacks/SilentFailingSendsAndUnchecked.sol, S11_SilentFailingSendsAndUnchecked-SendAttacks/readme.md
更新了合约安全S11_SilentFailingSendsAndUnchecked
=> 合约安全S11_SilentFailingSendsAndUnchecked更新

11_Modifier/readme.md
在第十一課有個小typo，我已經fix了！
There is a small typo in Lesson 11.
=> Fixed OpenZeppelin Typo on Lesson 11!!

README.md, Topics/Onchain_debug/en/readme.md, Topics/Onchain_debug/readme.md, Topics/readme.md
This series will be:
[Done] Lesson 1: Tools ( English | 中文 ) 
[Ongoing] Lesson 2: Warm up ( English | 中文 )
[Ongoing] Lesson 3: Writing p0c step by step (Real case1) ( English | 中文 )
Lesson 4: Writing p0c step by step (Real case2) ( English | 中文 )
=> OnChain Transaction Debugging: Lession 1: Tools

03_Function/readme.md
=> 合约中函数可见性默认值修复

26_DeleteContract/readme.md
=> Add description for eip-6049

39_Random/readme.md
修正有關鏈上生成隨機數 getRandomOnchain() 的描述與程式碼。
=> Update 第39講隨機數 readme.md

03_Function/readme.md
=> fix : 补全括号

README.md
=> feat(README.md):Add Solidity By Example Chinese Version Link

33_Airdrop/Airdrop.sol, 33_Airdrop/readme.md
修复： 第33讲：空投 代码中有Dos攻击风险
已在代码及readme中修复
=> 修复： 第33讲：空投 代码中有Dos攻击风险

S01_ReentrancyAttack/readme.md
Add PullPayment modal which is also a method recommended by OZ.(Since it's not widely used, it's not a common method but a supplement.)
=> Add pullpayment modal in ReentrancyAttack Protection

02_ValueTypes/readme.md
fix markdown warings and fill out &&
=> docs(02_valuetypes/readme.md): fix markdown warings and fill out &&

01_HelloWeb3/readme.md, 02_ValueTypes/readme.md, 03_Function/readme.md, 04_Return/readme.md
fix markdown's warnings and update some names
=> docs(04_return/readme.md): fix markdown's warnings and update some names

05_DataStorage/readme.md
=> docs(05_datastorage/readme.md): fix markdown's warning

07_Mapping/readme.md
=> docs(07_mapping/readme.md): fix markdown's warning

09_Constant/readme.md
fix the markdown's warning and fix the content details
=> docs(09_constant/readme.md): fix the markdown's warning and fix the content details

10_InsertionSort/InsertionSort.sol, 10_InsertionSort/readme.md
=> docs(10_insertionsort/readme.md): fix the markdown's warning

12_Event/Event.sol, 12_Event/readme.md
fix markdown's warnings and update some content
=> docs(12_event): fix markdown's warnings and update some content

11_Modifier/readme.md
fix markdown's warning and add some content
=> docs(11_modifier/readme.md): fix markdown's warning and add some content

10_InsertionSort/readme.md
=> docs(10_insertionsort/readme.md): fix lower "solidity"

15_Errors/readme.md
fix md's warings and fix content errors
=> docs(15_errors/readme.md): fix md's warings and fix content errors

17_Library/readme.md
=> docs(17_library/readme.md): fix md's warnings and fix content errors

18_Import/readme.md
=> docs(18_import/readme.md): fix md's warnings and fix content errors

19_Fallback/readme.md
=> docs(19_fallback/readme.md): fix md's warnings and fix content errors

21_CallContract/readme.md
=> docs(21_callcontract/readme.md): fix md's warnings and fix content errors

22_Call/readme.md
=> docs(22_call/readme.md): fix md's warnings and fix content errors

23_Delegatecall/readme.md
=> docs(23_delegatecall/readme.md): fix md's warnings and fix content errors

24_Create/readme.md
fix md's warnings and some content errors
=> docs(24_create/readme.md): fix md's warnings and some content errors

06_ArrayAndStruct/readme.md
=> docs(06_arrayandstruct/readme.md): fix contact

25_Create2/Create2.sol, 25_Create2/readme.md
=> docs(25_create2): fix md's warnings and content errors

26_DeleteContract/readme.md
=> docs(26_deletecontract/readme.md): fix md's warnings and content errors

27_ABIEncode/readme.md
=> docs(27_abiencode/readme.md): fix md's warnings and content errors

28_Hash/readme.md
=> docs(28_hash/readme.md): fix md's warnings and content errors

29_Selector/readme.md
=> docs(29_selector/readme.md): fix md's warnings and content errors

30_TryCatch/readme.md
=> docs(30_trycatch/readme.md): fix md's warnings and content errors

Topics/Tools/TOOL03_Ganache/readme.md
fix the word millisecond in the document of Ganache to second
=> Topics/Tools/TOOL03_Ganache/readme.md: fix ganache doc

Languages/en/23_Delegatecall_en/readme.md
@AmazingAng pls help review this PR. Thanks. :)
=> fix typos of chapter 23 (English Version)

04_Return/readme.md, 05_DataStorage/readme.md
Old reference: https://github.com/WTFAcademy/frontend/pull/125 More clear explaination for `memory` and `uint array`.
=> improve 04&05

Languages/en/13_Inheritance_en/readme.md
Update text, Gatherfather to Grandfather
=> fix: typo Gatherfather to Grandfather

.github/workflows/codespell.yml
=> fix(codespell): fix codespell

33_Airdrop/readme.md, README.md
* resolve : #662 
fix md's warnings and update some errors.
=> docs(33_airdrop): fix md warnings

README.md
S17内容章节已经merge，更新主页面目录将其加入。
Resolves #661
=> Add S17 to the main README contents table

31_ERC20/ERC20.sol, 31_ERC20/readme.md
* resolve : #657 
fix md's warnings and update some errors.
=> docs(31_erc20): update doc

32_Faucet/Faucet.sol, 32_Faucet/readme.md
* resolve : #659 
fix md's warnings and update some errors.
=> docs(32_faucet): update doc

33_Airdrop/Airdrop.sol
* resolve(修复) : #669 
fix modifier
=> docs(33_airdrop): fix modifier

Languages/en/20_SendETH_en/SendETH.sol
=> chore: fix typo

Languages/en/31_ERC20_en/readme.md, Languages/en/32_Faucet_en/readme.md, Languages/en/33_Airdrop_en/readme.md, Languages/en/34_ERC721_en/readme.md, Languages/en/35_DutchAuction_en/readme.md, Languages/en/36_MerkleTree_en/readme.md, Languages/en/37_Signature_en/readme.md, Languages/en/38_NFTSwap_en/readme.md, Languages/en/39_Random_en/readme.md, Languages/en/40_ERC1155_en/readme.md
It improves the english translation and helps learners' understanding.
=> Fixed Typo for Solidity lectures 31 - 40_en

S10_Honeypot/readme.md
=> new judgement

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/improvement.md, .github/ISSUE_TEMPLATE/typo_report.md
* resolve(修复) : #668 
add issue template
=> feat(issue): add issue template

37_Signature/readme.md
* resolve(修复) : #python web3库升级了，这里可以改下
=> [FIX] update python Web3.solidity_keccak

Languages/en/41_WETH_en/readme.md, Languages/en/42_PaymentSplit_en/readme.md, Languages/en/43_TokenVesting_en/readme.md, Languages/en/44_TokenLocker_en/readme.md, Languages/en/46_ProxyContract_en/readme.md, Languages/en/47_Upgrade_en/readme.md, Languages/en/48_TransparentProxy_en/readme.md, Languages/en/49_UUPS_en/readme.md, Languages/en/50_MultisigWallet_en/readme.md, Languages/en/51_ERC4626_en/readme.md, Languages/en/52_EIP712_en/readme.md, Languages/en/53_ERC20Permit/readme.md, Languages/en/54_CrossChainBridge/readme.md, Languages/en/56_DEX/readme.md, Languages/en/57_Flashloan/readme.md
It improves the English translation and helps learners' understanding.
=> Fixed Typo for Solidity lectures 41 - 57_en

README.md
链接挂了
plz close this issue 
- #684
=> [fix] fix the dead link

25_Create2/create2test.js, Languages/en/25_Create2_en/create2test.js, Languages/pt-br/25_Create2/create2test.js, Topics/Tools/TOOL06_Hardhat/.gitignore, Topics/Tools/TOOL06_Hardhat/hardhat.config.js, Topics/Tools/TOOL06_Hardhat/package-lock.json, Topics/Tools/TOOL06_Hardhat/package.json, Topics/Tools/TOOL06_Hardhat/readme.md, Topics/Tools/TOOL06_Hardhat/scripts/deploy.js, Topics/Tools/TOOL06_Hardhat/test/test.js
=> chore: update hardhat to 2.11.2

S14_TimeManipulation/readme.md
* resolve(修复) : #699 
fix typo
=> fix(typo): fix typo

19_Fallback/readme.md
修正中文语句重复😄
原文连续写了两个 “他们主要”，只需要一个。
=> fix: correct grammatical errors

36_MerkleTree/readme.md
1. 修改36_MerkleTree中proof数量计算公式
=> docs: 修改36_MerkleTree中proof数量计算公式

.codespellignore, Languages/en/48_TransparentProxy_en/TransparentProxy.sol, Languages/en/48_TransparentProxy_en/readme.md
fix code spell
codespell error
=> feat(codespell): fix code spell

03_Function/readme.md
添加状态变量定义的跳转链接
添加状态变量定义的跳转链接
添加状态变量定义的跳转链接,方便用户理解
=> #728 添加状态变量定义的跳转链接

Topics/Tools/TOOL07_Foundry/readme.md
+ 增加如何配置 `--rpc-url` 全局变量
+ 增加如何进行合约写操作 `cast send`
+ 增加如何使用命令行部署和开源合约 `forge create`
=> 优化 Foundry 相关内容

03_Function/readme.md
* resolve(修复) : # 修复文档对函数结构的描述中，参数的表达语法。
这里的文档看起来采用的是命令行帮助说明中的语法规则来展示函数结构。但是每个函数的参数应该是可选且不定个数的，不应该使用<>来进行解释，这里对此作出了一些修改。
关于命令行帮助说明的一些规则参考：
https://learn.microsoft.com/zh-cn/windows-server/administration/windows-commands/command-line-syntax-key
示例：
https://learn.microsoft.com/zh-cn/windows-server/administration/windows-commands/at
=> fix 文档中的语法问题修复

50_MultisigWallet/readme.md
修改表述错误: “并拼接到一起的到打包签名” 修改为 “并拼接到一起得到打包签名”。
=> fix: error correction

04_Return/readme.md
=> Fixes #772

09_Constant/readme.md
更正 `solidity` 版本號碼，應為 `0.8.21`
=> fix(readme.md): Update solidity version

38_NFTSwap/readme.md
勘误, 在onERC721Received函数时，少写个大括号
=> Fix syntax errors

Languages/en/14_Interface_en/readme.md
* resolve(修复) : #807 
1. fix `[abi-to-sol tool](https://gnidan.github.io/abi-to-sol/)`
2. replace `tokenid` with `tokenId`
=> fix: typos in 14_Interface_en/readme.md

53_ERC20Permit/readme.md
- [✅ ] Typo(勘误)
单词拼写错误
在第53课中，将secp256k1 修改为 keccak256
单词拼写错误，影响阅读理解。
=> Fix: lesson 53_ERC20Permit.Modify the content secp256k1 to keccak256

54_CrossChainBridge/crosschain.js, 54_CrossChainBridge/readme.md
=> Fixes #759 

.github/pull_request_template.md
* resolve : #826 
pr引用的相关issue，可以自动关闭
=> docs(pull_request_template.md): update pull_request_template.md

38_NFTSwap/NFTSwap.sol, 38_NFTSwap/readme.md, Languages/en/38_NFTSwap_en/NFTSwap.sol, Languages/en/38_NFTSwap_en/readme.md
* resolve: #829 
fix nftswap.sol bug
=> docs(38): fix nftswap.sol bug

47_Upgrade/readme.md
* resolve: 
because of #809,  i reviewed this readme.md.
=> docs(47): update doc

30_TryCatch/readme.md
* resolve: #800 
make the try-catch logic clearer.
=> docs(30): update public

.gitignore, mirror_gen.js
分发到其他网站
* resolve: #194 
执行 node mirror_gen.js 后，每个 readme 都会生成一个 readme_mirror.md 可以内容直接粘贴到 mirror 或者其他富文本平台，图片直接可以显示
后续可以考虑放在 action ，整理好格式，加上 api 自动分发
eg:
=> 方便 mirror 之类的平台分发，主要是图片格式

README.md
delete mirror link
* resolve: #
=> docs(readme): delete mirror link

README.md, Topics/ERC721/1_related_libraries/readme.md
=> feat(erc721-01): erc721-01

README.md, Topics/ERC721/2_Related_interface/readme.md
=> feat(02): erc721-02

README.md, Topics/ERC721/3_Erc721_main_contract/readme.md
=> feat(erc721-03): erc721-03

53_ERC20Permit/readme.md
=> fix readme

Languages/en/20_SendETH_en/SendETH.sol, Languages/en/20_SendETH_en/readme.md
=> docs(codespell): fix codespell

07_Mapping/Mapping.sol
* resolve: #864
Supplement _KeyType
=> docs(07_mapping): supplement KeyType
