AmazingAng/WTF-Solidity

16_Overloading/readme.md

更新 **16. 函数重载** `README.md` 中函数选择器的link

更新README的link

---

39_Random/readme.md

用球与杯子的例子解释了O(n)不初始化ids[]的随机排列算法

添加了对nft tokenid随机排列的解释

---

S02_SelectorClash/readme.md

executeCrossChainTx() 函数的第4个参数类型为 uint64， 需要传入0 而非 0x

docs:  替换参数

---

38_NFTSwap/NFTSwap.sol
38_NFTSwap/readme.md

在38章节中，购买NFT后触发的Purchase事件应该记录NFT的购买价格，而不是记录购买者的ETH余额

fix: 修复38章节中，记录Purchase事件参数错误的问题

---

37_Signature/readme.md
38_NFTSwap/readme.md
41_WETH/readme.md
43_TokenVesting/readme.md

add language in md code block in order to show code highlight

fix: code highlight

---

Topics/Translation/DiveEVM2017/DiveEVM2017-Part6.md

Update DiveEVM2017-Part6.md fix bytes count error
示例参数为 32 bit 需要用 8 位 16 进制编码表示，文档中 32 位数据【0xc0fefe】少了 2 位 16 进制编码

fix[DiveEVM2017]: Part6.md bytes count error

---

Languages/en/27_ABIEncode_en/readme.md

docs: fix typo in 27_ABIEncode_en/readme.md

---

03_Function/Function.sol
03_Function/readme.md

fix some markdown's warnings and update some doc errors

docs(03_function/readme.md): fix some markdown's warnings

---

06_ArrayAndStruct/ArrayAndStruct.sol
06_ArrayAndStruct/readme.md

docs(06_arrayandstruct): fix markdown's warning

---

08_InitialValue/readme.md

docs(08_initialvalue/readme.md): fix markdown's warning

---

13_Inheritance/DiamondInheritance.sol
13_Inheritance/readme.md

fix markdown's warnings and fix some content errors

docs(13_inheritance/readme.md): fix markdown's warnings

---

35_DutchAuction/DutchAuction.sol

```
@openzeppelin/contracts/access/Ownable.sol
/**
* @dev Initializes the contract setting the address provided by the deployer as the initial owner.
*/
constructor(address initialOwner) {
if (initialOwner == address(0)) {
revert OwnableInvalidOwner(address(0));
}
_transferOwnership(initialOwner);
}
```
`DutchAuction` extends `Ownable` but does not initialize `initialOwner`. Compiler throws 
```
TypeError: No arguments passed to the base constructor. Specify the arguments or mark "DutchAuction" as abstract.
--> 35_DutchAuction/DutchAuction.sol:7:1:
|
7 | contract DutchAuction is Ownable, ERC721 {
| ^ (Relevant source part starts here and spans across multiple lines).
Note: Base constructor parameters:
--> @openzeppelin/contracts/access/Ownable.sol:38:16:
|
38 |     constructor(address …
```

Fix Compilation Error Due to Missing Constructor Arguments in DutchAuction.sol & Fix Typo

---

S10_Honeypot/Honeypot.sol
S10_Honeypot/readme.md

According to the [issue](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3838), hooks of ERC20 have been removed. `_update()` is the new function instead.
@AmazingAng Please help review.

Update pi xiu contract's ERC20 function

---

Languages/en/15_Errors_en/readme.md

In 15th Chapter's `Errors` part for English, there is a redundant symbol ` :

docs: remove redundant "`" in 15th Errors for English

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/document.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/improvement-report.yml

* resolve(修复) : 
plz close this issue :
- #668 
测试地址
https://github.com/fuchanghai/java-github-action/issues/new/choose
效果如下
- bug
- doc
- improve
- faq

Feature #add issue temp

---

36_MerkleTree/readme.md

使用MerkleProof庫來驗證時，輸入的變數是地址0的Hash，是因為上述文章使用了hashLeaves這個選項。
* resolve(修复) : 更正文章內描述

修改MerkleProof庫中的文字說明

---

17_Library/readme.md

* resolve(修复) : https://github.com/WTFAcademy/WTF-Solidity/pull/6
fix typo

docs(017): fix typo

---

S05_Overflow/readme.md

此PR解决掉S05_overflow上的oz库上safeMath链接失效的问题，将老的无法访问的链接更改到可访问的链接

解决Safemath 库连接失效问题

---

Languages/en/20_SendETH_en/readme.md

If `send()` fails, the transaction will **not** be reverted.
* resolve(修复) : #813 
1. fix: If `send()` fails, the transaction will **not** be reverted.

fix: typo in 20_SendETH_en/readme.md

---

56_DEX/readme.md

添加 WTF-DApp 课程 https://github.com/WTFAcademy/WTF-Dapp 到文档中，引导对 DEX 开发感兴趣的同学继续深入学习

docs(56): Add WTF-Dapp link

---

50_MultisigWallet/MultisigWallet.sol

- [✔ ] BUG(程序错误)
如果success为false，那require放在这里会导致回滚，后面的else逻辑不会执行。还请指教。
* resolve: #
注释这行 require(success , "WTF5004");
//require(success , "WTF5004");

如果success为false，那require放在这里会导致回滚，后面逻辑并不会执行

---

Languages/pt-br/38_NFTSwap/NFTSwap.sol

This PR resolves the compilation issues in `NFTSwap.sol` and improves its functionality by:
- Correcting undeclared variable `_order` by mapping it correctly to `nftList`.
- Updating and fixing import paths for ERC721 dependencies to match the directory structure.
- Implementing proper validations for key functions:
- `list`: Ensures only the owner can list NFTs and validates the approval.
- `purchase`: Checks sufficient payment and proper transfer logic.
- `revoke`: Verifies the ownership before revoking an order.
- `update`: Ensures only the owner can update the price.
- Successfully compiled the contract and verified output artifacts.
* resolve: #830
This PR fixes the issues that caused the `NFTSwap.sol` contract to fail compilation and ensures proper functioning of its core methods …

Daniil Krizhanovskyi <arecibo@fedora.home>
